### ISSUE TITLE
services.yaml

### ISSUE THREAD

**Issue by NickoM31** [odiseoteam/SyliusMailchimpPlugin#2]
I had to override your services.yaml because there is a writing error.
In your service odiseo.mailchimp_plugin.mailchimp: the arguments should be "% odiseo.mailchimp_plugin.mailchimp_api_key%" (your is "% odiseo.mailchimp_plugin.mailchimp_apikey%") and "% odiseo.mailchimp_plugin.mailchimp_default_list_id%" (your is "% odiseo.mailchimp_plugin.mailchimp_default_listid% ")
Cordially.

**Comment by odiseoteam** [comment]
Hi @NickoM31, we released a new version of this plugin. Please, let me know if this issue has been fixed.
